# -*- coding: utf-8 -*-
"""New.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6OKEdIj0luP_1PVIqcOu-4SmtFc9DwO
"""

print("Hello World!")

print("Good Morning!")

import seaborn as sb

import tensorflow as tf

tf.__version__

import numpy as np
np.__version__

import numpy as np
import pandas as pd

pd.__version__

sb.__version__

my_list = [1,2,3]

np.array(my_list)

my_list

nested_list = [[1,2],[3,4],[5,6]]

np.array(nested_list)

nested_list

np.arange(0,9,3)

np.zeros(2)

np.zeros((2,5),dtype=int)

np.ones((4,4),dtype=int)

np.linspace(1,10,7)

np.eye(5)

np.random.rand(2)

np.random.rand(2,3)

np.random.rand(3,4)

np.random.randn(3,4)

np.random.randint(1,100,5)

np.random.seed(42)
np.random.rand(4)

arr = np.arange(25)

arr

ranarr = np.random.randint(0,50,10)

ranarr

arr.shape

arr = arr.reshape(5,5)

arr

arr.shape

ranarr

ranarr.max()

ranarr.argmax()

ranarr.min()

ranarr.argmin()

ranarr.dtype

myarr = np.random.rand(4)

myarr

myarr.dtype

new_arr = np.arange(1,10)

new_arr

new_arr[2]

new_arr[3:]

new_arr[new_arr<=3]

new2d = np.arange(0,16).reshape(4,4)

new2d.dtype

new2d.shape

new2d

new2d.sum(axis=0)

new2d.sum(axis=1)

np.ones(5) * 5

new2d[2:,1:]

import pandas as pd

arr = np.arange(1,5)

arr

labels = ['a','b','c','d']

pd.Series(arr,labels)

salesq1 = pd.Series(data=[250,300,150,25],index=['Usa','China','India','Nepal'])

salesq1

salesq2 = pd.Series(data=[150,400,200,150],index=['Usa','China','India','Japan'])

salesq2

salesq1+salesq2

index = ['A','B','C','D','E']

column = ['Q','R','S','T']

np.random.seed(42)
data = np.random.randint(-100,100,(5,4))

data

df = pd.DataFrame(data,index,column)

df

type(df)

type(df['Q'])

df[['Q','T']]

df['U'] = df['Q']+df['S']

df

#df = df.drop('New',axis=1)

df

type(df.loc['A'])

df.loc[['A','D']]

df['R']

df.iloc[[2,1,-1]]

df

df.loc[['A','D'],['S','U']]

df.iloc[[0,3],[2,4]]

df

df[df > 0]

df

df[df['R'] > 0].iloc[[0,2],[1,3]]
#df.loc['B']

df

(df['Q']>5) & (df['U']>0)

df[(df['Q']>5) & (df['U']>0)]

df

new_index = ['DL','RJ','MH','GJ','HR']

df['Sates'] = new_index

df

df = df.set_index('Sates')

df

df.columns

df.index

df.describe()

df.info()

df.dtypes

#from google.colab import files
#uploaded = files.upload()

#import io

#df = pd.read_csv(io.BytesIO(uploaded['Universities.csv']))

#df

#df.info()

#df.describe()

#df.head()

#df.groupby('Year').sum().sort_index(ascending=False)

#df.groupby(['Year','Sector']).sum()

def get_milk(amount,price):
  print("Go to building")
  print("Buy " + str(amount) + " Cartoons of milk")
  print("Pay " + str(price) + " $")
  print(type(amount))
  print("Come back to room." )

get_milk(3,6)

"""# Gradient Descent"""

df

type(df)

import numpy as np

sample_array = np.array([1,2,3])

sample_array.shape

import pandas as pd

sample_array.size

sample_array

sample_array.dtype

ones = np.ones((2,3))

ones

ones.dtype

type(ones)

import random

np.random.seed(7)
np_array_1 = np.random.random((5,3))

np_array_1

random_array_2 = np.random.randint(10,size=(5,3))
np.random.seed(5)
random_array_2

np.unique(random_array_2)

a1 = np.random.randint(7,size=(3,2,3,4))

a1

a1.ndim

a1[:,:,:,:3]

a1

a2 = np.random.randint(7,size=(2,3))

a3 = np.random.randint(7,size=(2,1))

a3.shape

a2.shape

a4 = a3.T.dot(a2)

a4

import matplotlib.pyplot as plt

plt.hist(a4)

plt.plot([1,2,3])
plt.show()

